#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define COMPANY_NAME "PowerSyntez"
#define PROGRAM_NAME "PersoHost"

#define MASTER_MODE_ACCESS_KEY "1995"

#define POSTGRES_SERVER_DEFAULT_IP "localhost"
#define POSTGRES_SERVER_DEFAULT_PORT 5432
#define POSTGRES_SERVER_DEFAULT_USER_NAME "postgres"
#define POSTGRES_SERVER_DEFAULT_PASSWORD "1995"
#define POSTGRES_DATABASE_DEFAULT_NAME "TransponderDatabase"

#define PERSO_SERVER_DEFAULT_IP "127.0.0.1"
#define PERSO_SERVER_DEFAULT_PORT 6000
#define IP_PORT_MAX_VALUE 65535

#define DATA_BLOCK_PART_WAIT_TIME 500
#define ONETIME_TRANSMIT_DATA_SIZE 10240
#define DATA_BLOCK_MAX_SIZE 250000

#define CLIENT_MAX_COUNT 5
#define CLIENT_CONNECTION_MAX_DURATION 10000

#endif // DEFINITIONS_H
