name: build PersoServer git
run-name: build PersoServer
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-23.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build persoserver
        run: |
          cd ${{ gitea.workspace }}
          mkdir build
          cd build
          cmake -G "Ninja" ..
          ninja
